# Bản đồ tên thành phố phổ biến
CITY_MAP = {
    "hanoi": "Hà Nội",
    "hochiminh": "TP. Hồ Chí Minh",
    "tphcm": "TP. Hồ Chí Minh",
    "hcm": "TP. Hồ Chí Minh",
    "haiphong": "Hải Phòng",
    "danang": "Đà Nẵng",
    "cantho": "Cần Thơ",
    "angiang": "An Giang",
    "bariavungtau": "Bà Rịa - Vũng Tàu",
    "bacgiang": "Bắc Giang",
    "backan": "Bắc Kạn",
    "baclieu": "Bạc Liêu",
    "bacninh": "Bắc Ninh",
    "bentre": "Bến Tre",
    "binhdinh": "Bình Định",
    "binhduong": "Bình Dương",
    "binhphuoc": "Bình Phước",
    "binhthuan": "Bình Thuận",
    "camau": "Cà Mau",
    "caobang": "Cao Bằng",
    "daklak": "Đắk Lắk",
    "daknong": "Đắk Nông",
    "dienbien": "Điện Biên",
    "dongnai": "Đồng Nai",
    "dongthap": "Đồng Tháp",
    "gialai": "Gia Lai",
    "hagiang": "Hà Giang",
    "hatinh": "Hà Tĩnh",
    "haiduong": "Hải Dương",
    "haugiang": "Hậu Giang",
    "hoabinh": "Hòa Bình",
    "hungyen": "Hưng Yên",
    "khanhhoa": "Khánh Hòa",
    "kiengiang": "Kiên Giang",
    "kontum": "Kon Tum",
    "laichau": "Lai Châu",
    "lamdong": "Lâm Đồng",
    "langson": "Lạng Sơn",
    "laocai": "Lào Cai",
    "longan": "Long An",
    "namdinh": "Nam Định",
    "nghean": "Nghệ An",
    "ninhbinh": "Ninh Bình",
    "ninhthuan": "Ninh Thuận",
    "phutho": "Phú Thọ",
    "phuyen": "Phú Yên",
    "quangbinh": "Quảng Bình",
    "quangnam": "Quảng Nam",
    "quangngai": "Quảng Ngãi",
    "quangninh": "Quảng Ninh",
    "quangtri": "Quảng Trị",
    "soctrang": "Sóc Trăng",
    "sonla": "Sơn La",
    "tayninh": "Tây Ninh",
    "thaibinh": "Thái Bình",
    "thainguyen": "Thái Nguyên",
    "thanhhoa": "Thanh Hóa",
    "thuathienhue": "Thừa Thiên - Huế",
    "tiengiang": "Tiền Giang",
    "travinh": "Trà Vinh",
    "tuyenquang": "Tuyên Quang",
    "vinhlong": "Vĩnh Long",
    "vinhphuc": "Vĩnh Phúc",
    "yenbai": "Yên Bái"
}