services:
  hadoop-base:
    build:
      context: ./hadoop-base
      dockerfile: Dockerfile
    image: hadoop-base1

  hadoop-master:
    build:
      context: ./master
      dockerfile: Dockerfile
    image: hadoop-master1
    container_name: hadoop-master
    hostname: ducdung-master
    environment:
      - ROLE=master
    depends_on:
      - hadoop-base
    ports:
      - "9870:9870" # NameNode Web UI
      - "8088:8088" # ResourceManager Web UI
      - "9864:9864" # DataNode Web UI (optional)
      - "8042:8042" # NodeManager Web UI (optional)
      - "4040:4040" # Spark Web UI (optional)
    volumes:
      - ./hadoop_data/namenode:/home/hadoopducdung/hadoop/hadoop_data/hdfs/namenode
      - hadoop-logs:/home/hadoopducdung/hadoop/logs
      - ../spark_jobs/Code:/opt/spark_jobs
    entrypoint: [ "/usr/local/bin/entrypoint.sh" ]
  hadoop-slave:
    build:
      context: ./slave
      dockerfile: Dockerfile
    image: hadoop-slave1
    container_name: ducdung-slave1
    depends_on:
      - hadoop-base
    volumes:
      - ./hadoop_data/datanode1:/home/hadoopducdung/hadoop/hadoop_data/hdfs/datanode
    entrypoint: [ "/usr/local/bin/entrypoint.sh" ]
  hadoop-slave2:
    build:
      context: ./slave
      dockerfile: Dockerfile
    image: hadoop-slave
    container_name: ducdung-slave2
    depends_on:
      - hadoop-base
    volumes:
      - ./hadoop_data/datanode2:/home/hadoopducdung/hadoop/hadoop_data/hdfs/datanode
    entrypoint: [ "/usr/local/bin/entrypoint.sh" ]
  metastore-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: metastore
      MYSQL_USER: hive
      MYSQL_PASSWORD: hive
    volumes:
      - metastore-db-data:/var/lib/mysql
  hive-metastore:
    user: "hadoopducdung"
    build: ./hive
    container_name: hive-metastore
    hostname: hive-metastore
    environment:
      HIVE_METASTORE_DB_HOST: metastore-db
      HIVE_METASTORE_DB_USER: hive
      HIVE_METASTORE_DB_PASS: hive
      HADOOP_CONF_DIR: /opt/hadoop/etc/hadoop
    depends_on:
      - hadoop-master
      - metastore-db
    command: [ "hive", "--service", "metastore" ]
    ports:
      - "9083:9083" # Metastore Thrift
    volumes:
      - hive-warehouse:/user/hive/warehouse
  # Hive Metastore + Server2
  hive-server:
    user: "hadoopducdung"
    build: ./hive
    container_name: hive-server
    hostname: hive-server
    environment:
      HIVE_METASTORE_DB_HOST: metastore-db
      HIVE_METASTORE_DB_USER: hive
      HIVE_METASTORE_DB_PASS: hive
      HADOOP_CONF_DIR: /opt/hadoop/etc/hadoop
    depends_on:
      - hadoop-master
      - metastore-db
    ports:
      - "10000:10000" # HiveServer2
      - "10002:10002" # Beeline
    volumes:
      - hive-warehouse:/user/hive/warehouse
      - ./hive_scripts/HiveSQL:/opt/hive_scripts

volumes:
  hdfs-name:
  hdfs-data1:
  hdfs-data2:
  hadoop-logs:
  hive-warehouse:
  metastore-db-data:
